hdeolekar-fp/src/main/java/edu/iit/sat/itmd4515/hdeolekar/web/LoginController.java
package edu.iit.sat.itmd4515.hdeolekar.web;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.Stateless;
import javax.faces.application.FacesMessage;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

import edu.iit.sat.itmd4515.hdeolekar.service.CustomerService;


/**
 *
 * Servlet implementation class LoginController. This controller is used to
 * navigate based on the user logged in.
 * @author Prof. Scott
 * @author Harshal
 */
@Named
@Stateless
@RequestScoped
public class LoginController extends BaseController{
	private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

	@NotNull(message = "You must enter a username.")
	private String username;
	@NotNull(message = "You must enter a password.")
	private String password;

	public LoginController() {
		super();
	}


	/**
	 * Returns the logged in username
	 * @return
	 */
	public String getRemoteUser() {
		this.context = FacesContext.getCurrentInstance();
		return context.getExternalContext().getRemoteUser();
	}

	/**
	 * Returns true if logged in user is customer
	 * @return true if logged in user is customer, else returns false
	 */
	public boolean isCustomer() {
		this.context = FacesContext.getCurrentInstance();
		return context.getExternalContext().isUserInRole("CUSTOMER_ROLE");
	}

	/**
	 * Returns true if logged in user is banker
	 * @return true if logged in user is banker, else returns false
	 */
	public boolean isBanker() {
		this.context = FacesContext.getCurrentInstance();
		return context.getExternalContext().isUserInRole("BANKER_ROLE");
	}

	/**
	 * Returns true if logged in user is admin
	 * @return true if logged in user is admin, else returns false
	 */
	public boolean isAdmin() {
		this.context = FacesContext.getCurrentInstance();
		return context.getExternalContext().isUserInRole("ADMIN_ROLE");
	}
	 // action methods
    /**
     * Handles login for the user
     * @return welcome page
     */
    public String doLogin() {
    	String redirectURL = "";
       LOG.info("Request received by LoginController..");
       System.out.println("Request received by LoginController..");
        try {
        	this.context = FacesContext.getCurrentInstance();
        	HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            request.login(username, password);
    		// If it is a customer page, show customers home page else show bankers
    		// home page.
    		if (isCustomer()) {
    			System.out.println("User Role is Customer");
    			//requestDispatcher = request.getRequestDispatcher("/customer");
    			redirectURL = "/customer/layout/welcome.xhtml";
    		} else if (isBanker() || isAdmin()) {
    			System.out.println("User Role is Banker or admin");
    			//requestDispatcher = request.getRequestDispatcher("/banker");
    			//redirectURL = "/banker/welcome.xhtml";
    			redirectURL = "/banker/layout/welcome.xhtml";
    		}
    		//requestDispatcher.forward(request, response);
        } catch (ServletException ex) {
            // login failed, first log the message
        	ex.printStackTrace();
            LOG.log(Level.SEVERE, null, ex);
            // provide useful message to user - NOT the actual exception
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Login",
            		"Username and/or Password was not valid."));
            // short circuit the navigation and send back to login page with message
            return "/security/login.xhtml";
        }

        return redirectURL+"?faces-redirect=true";
    }

    /**
     * Logs out the user
     * @return welcome page.
     */
    public String doLogout() {
        try {
        	this.context = FacesContext.getCurrentInstance();
            HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
            req.logout();
            System.out.println("logging out-- "+context.getExternalContext().getRequest());
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Logout", "Failed to logout."));
            return "/welcome.xhtml";
        }

        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "You have logged out", "You have logged out successfully.  Please don't forget to close your browser."));
        return "/welcome.xhtml";
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns registration view.
     * @return
     */
    public String showRegistrationPage() {
		System.out.println("register page called..");
		return "register.xhtml";
	}

    public String showAddressDetailsPage() {
		System.out.println("Address page called..");
		return null;
	}
}

hdeolekar-fp/src/main/webapp/default/layout/cancelLoanApplication.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="./../../WEB-INF/templates/publicTemplate2.xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

	<ui:define name="title">
        Update Loan Application
    </ui:define>


	<ui:define name="content">

		<div class="content-wrapper">

			<h:outputStylesheet library="plugins/datepicker/" name="datepicker3.css" />
<!-- 			<h:outputStylesheet library="plugins/iCheck/minimal/" name="_all.css" /> -->
			<!-- Content Header (Page header) -->
			<section class="content-header">
			<h1>
				Blank page <small>it all starts here</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Examples</a></li>
				<li class="active">Blank page</li>
			</ol>
			</section>

			<!-- Main content -->
			<section class="content"> <!-- Default box -->
			<div class="box">
				<div class="box-header with-border">
						<label>Loan Application ID</label>

			              <div class="input-group input-group-sm col-md-3">
			                <!-- <input type="text" class="form-control"/> -->

			                    <h:form role="form">
			                    	<span class="input-group-btn">
			                    		<h:inputText id="val" binding="#{loanApplicationID}"
			                    					type="text" class="form-control"/>

			                      		<!-- <input type="submit" class="btn btn-info btn-flat">Go!</button> -->
			                    		<h:commandButton class="btn btn-info btn-flat" style="outline:0"
											value="Go!" action="#{loanApplicationController.getLoanApplicationById(loanApplicationID.value)}">
											<f:ajax execute="val" render=":updateForm"></f:ajax>
										</h:commandButton>
			                    	</span>
			                    </h:form>
			              </div>

					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool"
							data-widget="collapse" data-toggle="tooltip" title="Collapse">
							<i class="fa fa-minus"></i>
						</button>
						<button type="button" class="btn btn-box-tool"
							data-widget="remove" data-toggle="tooltip" title="Remove">
							<i class="fa fa-times"></i>
						</button>
					</div>
				</div>
				<div class="box-body">
					<div class="row">
						<!-- left column -->
						<div class="col-md-6">
							<!-- general form elements -->
							<div class="box box-primary">
								<div class="box-header with-border">
									<h3 class="box-title">Loan Application Details</h3>
								</div>
								<!-- /.box-header -->
								<!-- form start -->
								<h:form id="updateForm" role="form">
									<div class="box-body">
										<div class="form-group">
						                  <label for="loanType">Loan Type</label>
						                  	<h:selectOneMenu class="form-control disabled" id="loanType"
								                  		  value="#{loanApplicationController.loanApplication.loanType}" >
								                    <f:selectItem itemValue="HOME_LOAN" itemLabel="Home Loan" />
								                    <f:selectItem itemValue="CAR_LOAN" itemLabel="Car Loan" />
								                    <f:selectItem itemValue="EDUCATION_LOAN" itemLabel="Education Loan" />
								                    <f:selectItem itemValue="USED_CAR_LOAN" itemLabel="Used Car Loan" />
								            </h:selectOneMenu>
						                </div>
										<div class="form-group">
											<label for="loanAmount">Loan Amount</label> <h:inputText
												type="text" class="form-control disabled" id="loanAmount"
												placeholder="Enter Loan Amount"
												value="#{loanApplicationController.loanApplication.loanAmount}" />
										</div>
										<div class="form-group">
											<label for="monthlyIncome">Monthly Income</label> <h:inputText
												type="text" class="form-control" id="monthlyIncome"
												placeholder="Enter social security"
												value="#{loanApplicationController.loanApplication.monthlyIncome}" />
										</div>
										<div class="form-group">
											<label for="email">Email</label>
											<div class="input-group">
							                  <div class="input-group-addon">
							                    <i class="fa fa-envelope"></i>
							                  </div>
							                  <h:inputText type="text" class="form-control pull-right disabled" id="email"
							                  value="#{loanApplicationController.loanApplication.email}" />
							                </div>
										</div>
										<!-- phone mask -->
										<div class="form-group">
							                <label>Phone:</label>

							                <div class="input-group">
							                  <div class="input-group-addon">
							                    <i class="fa fa-phone"></i>
							                  </div>
							                  <h:inputText type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask=""
							                  value="#{loanApplicationController.loanApplication.phone}" />
						                	</div>
						                </div>
										<div class="form-group">
						                  <label for="collateralType">Collateral Type</label>
						                  	<h:selectOneMenu class="form-control disabled"  id="collateralType"
								                  		  value="#{loanApplicationController.collateral.collateralType}" >
								                    <f:selectItem itemValue="FIXED_DEPOSIT" itemLabel="Fixed Deposit" />
								                    <f:selectItem itemValue="HOUSE" itemLabel="House" />
								                    <f:selectItem itemValue="FLAT" itemLabel="Flat" />
								                    <f:selectItem itemValue="NON_AGRICULTURAL_LAND" itemLabel="Non Agricultural Land" />
											</h:selectOneMenu>
						              	</div>
						              	<div class="form-group">
											<label for="marketValue">Market Value</label> <h:inputText
												type="text" class="form-control disabled" id="marketValue"
												placeholder="Enter social security"
												value="#{loanApplicationController.loanApplication.collateral.marketValue}" />
										</div>
									</div>
									<!-- /.box-body -->
									<div class="box-footer">
									<h:commandButton class="btn btn-primary"
												value="Cancel" action="#{loanApplicationController.cancelLoanApplication()}">

									</h:commandButton>

									</div>
								</h:form>
							</div>
							<!-- /.box -->
						</div>
						<!-- col-md-6 -->
					</div>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">Footer</div>
				<!-- /.box-footer-->
			</div>
			<!-- /.box --> </section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->
		<h:outputScript name="plugins/datepicker/bootstrap-datepicker.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/iCheck/icheck.min.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.date.extensions.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.extensions.js" target="body"></h:outputScript>


		<h:outputScript target="body">
		$(function () {
			$("[data-mask]").inputmask();
		    //Date picker
		    $('#datepicker').datepicker({
		      autoclose: true
		    });

		    //iCheck for checkbox and radio inputs
		    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
		      checkboxClass: 'icheckbox_minimal-blue',
		      radioClass: 'iradio_minimal-blue'
		    });
		 });

		 function addCoBorrower() {

		 }
	</h:outputScript>
	</ui:define>

</ui:composition>

hdeolekar-fp/src/main/webapp/default/layout/updateProfile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="./../../WEB-INF/templates/publicTemplate2.xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
	<ui:define name="title">
        Update Profile
    </ui:define>


	<ui:define name="content">

		<div class="content-wrapper">

			<h:outputStylesheet library="plugins/datepicker/" name="datepicker3.css" />
<!-- 			<h:outputStylesheet library="plugins/iCheck/minimal/" name="_all.css" /> -->
			<!-- Content Header (Page header) -->
			<section class="content-header">
			<h1>
				Update Profile <small>Please appropriate details</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Examples</a></li>
				<li class="active">Blank page</li>
			</ol>
			</section>

			<!-- Main content -->
			<section class="content"> <!-- Default box -->
			<div class="box">
				<ui:fragment rendered="#{loginController.banker}">
					<div class="box-header with-border">
						<label>Please enter customer ID</label>

						<div class="input-group input-group-sm col-md-3">
							<!-- <input type="text" class="form-control"/> -->

							<h:form role="form">
								<span class="input-group-btn"> <h:inputText id="val"
										binding="#{customerID}" type="text" class="form-control" /> <!-- <input type="submit" class="btn btn-info btn-flat">Go!</button> -->
									<h:commandButton class="btn btn-info btn-flat"
										style="outline:0" value="Go!"
										action="#{customerController.getCustomerById(customerID.value)}">
										<f:ajax execute="val" render=":customerForm"></f:ajax>
									</h:commandButton>
								</span>
							</h:form>
						</div>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse" data-toggle="tooltip" title="Collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove" data-toggle="tooltip" title="Remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
				</ui:fragment>
				 <h:dataTable value="#{customerController.getCustomerByUsername(loginController.remoteUser)}">
				 </h:dataTable>
				<h:panelGroup id="customerForm">
						<h:panelGroup rendered="#{not empty customerController.customer}">
							<div class="box-body">
								<div class="row">
									<!-- left column -->
									<div class="col-md-6">
										<!-- general form elements -->
										<div class="box box-primary">
											<div class="box-header with-border">
												<h3 class="box-title">Quick Example</h3>
											</div>
											<!-- /.box-header -->
											<!-- form start -->
											<h:form role="form">
												<div class="box-body">
													<div class="form-group">
														<label for="firstName">First Name</label>
														<h:inputText type="text" class="form-control"
														required="true" requiredMessage="Please enter first name"
															id="firstName" placeholder="Enter first name"
															value="#{customerController.customer.firstName}" />
														<h:message for="firstName" style="color:red" />
													</div>
													<div class="form-group">
														<label for="lastName">Last Name</label>
														<h:inputText type="text" class="form-control" id="lastName"
															required="true" requiredMessage="Please enter last name"
															placeholder="Enter last name"
															value="#{customerController.customer.lastName}" />
															<h:message for="lastName" style="color:red" />
													</div>
													<div class="form-group">
														<label for="ssn">Social Security Number</label>
														<h:inputText type="text" class="form-control" id="ssn"
														required="true" requiredMessage="Please enter ssn"
															placeholder="Enter social security"
															value="#{customerController.customer.socialSecurityNumber}" />
															<h:message for="ssn" style="color:red" />
													</div>
													<!-- <div class="form-group">
		                							<label> Gender
		                  								<input type="radio" name="male" class="minimal"/>
		                							</label>
		                							<label>
		                  								<input type="radio" name="female" class="minimal"/>
		                							</label>
		              							</div> -->
													<div class="form-group">
														<label for="datepicker">Date Of Birth</label>
														<div class="input-group date">
															<div class="input-group-addon">
																<i class="fa fa-calendar"></i>
															</div>
															<h:inputText id="dateOfBirth"
																value="#{customerController.customer.dateOfBirth}"
																required="true" requiredMessage="Please enter date of birth"
																type="text" class="form-control"
																data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
																<f:convertDateTime pattern="M-d-yyyy" />
															</h:inputText>
															<h:message for="dateOfBirth" style="color:red" />
														</div>
													</div>
													<!-- phone mask -->
													<div class="form-group">
														<label>US phone mask:</label>

														<div class="input-group">
															<div class="input-group-addon">
																<i class="fa fa-phone"></i>
															</div>
															<h:inputText id="phone" type="text" class="form-control"
															required="true" requiredMessage="Please enter phone number"
																data-inputmask='"mask": "(999) 999-9999"' data-mask=""
																value="#{customerController.customer.phone}" />
																<h:message for="phone" style="color:red" />
														</div>
														<!-- /.input group -->
													</div>
													<!-- /.form group -->
													<div class="form-group">
														<label for="address1">Address 1</label>
														<h:inputText id="address1" type="text" class="form-control"
															placeholder="Enter address line 1"
															required="true" requiredMessage="Please enter address"
															value="#{customerController.customer.address.address1}" />
														<h:message for="address1" style="color:red" />
													</div>
													<div class="form-group">
														<label for="address2">Address 2</label>
														<h:inputText id="address2" type="text" class="form-control"
															placeholder="Enter address line 2"
															value="#{customerController.customer.address.address2}" />
														<h:message for="address2" style="color:red" />
													</div>
													<div class="form-group">
														<label for="city">City</label>
														<h:inputText id="city"  type="text"
														required="true" requiredMessage="Please enter city"
															class="form-control" placeholder="Enter city"
															value="#{customerController.customer.address.city}" />
														<h:message for="city" style="color:red" />
													</div>
													<div class="form-group">
														<label for="state">State</label>
														<h:inputText id="state" type="text" class="form-control"
															placeholder="Enter state"
															required="true" requiredMessage="Please enter state"
															value="#{customerController.customer.address.state}" />
														<h:message for="state" style="color:red" />
													</div>
													<div class="form-group">
														<label for="country">Country</label>
														<h:inputText id="country" type="text" class="form-control"
															placeholder="Enter country"
															required="true" requiredMessage="Please enter country"
															value="#{customerController.customer.address.country}" />
														<h:message for="country" style="color:red" />
													</div>
												</div>
												<!-- /.box-body -->

												<div class="box-footer">
													<h:commandButton class="btn btn-primary" value="Save"
														action="#{customerController.updateCustomer()}" />

												</div>
											</h:form>
										</div>
										<!-- /.box -->
									</div>
									<!-- col-md-6 -->
								</div>
							</div>
						</h:panelGroup>
				</h:panelGroup>

				<!-- /.box-body -->
				<div class="box-footer">Footer</div>
				<!-- /.box-footer-->
			</div>
			<!-- /.box --> </section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->
		<h:outputScript name="plugins/datepicker/bootstrap-datepicker.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/iCheck/icheck.min.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.date.extensions.js" target="body"></h:outputScript>
		<h:outputScript name="plugins/input-mask/jquery.inputmask.extensions.js" target="body"></h:outputScript>


		<h:outputScript target="body">
		$(function () {
			$("[data-mask]").inputmask();
		    //Date picker
		    $('#datepicker').datepicker({
		      autoclose: true
		    });

		    //iCheck for checkbox and radio inputs
		    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
		      checkboxClass: 'icheckbox_minimal-blue',
		      radioClass: 'iradio_minimal-blue'
		    });
		 });
	</h:outputScript>
	</ui:define>

</ui:composition>

hdeolekar-fp/src/main/webapp/default/layout/viewInstallmentDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="./../../WEB-INF/templates/publicTemplate2.xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

	<ui:define name="title">
        Banker Home Page
    </ui:define>

	<ui:define name="content">
		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
			<h1>
				Data Tables <small>advanced tables</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Tables</a></li>
				<li class="active">Data tables</li>
			</ol>
			</section>

			<!-- Main content -->
			<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<label>Loan Application ID</label>
							<div class="input-group input-group-sm col-md-3">
								<!-- <input type="text" class="form-control"/> -->

								<h:form role="form">
									<span class="input-group-btn"> <h:inputText id="val"
											binding="#{loanApplicationID}" type="text" class="form-control" />
										<h:commandButton class="btn btn-info btn-flat"
											style="outline:0" value="Go!"
											action="#{paymentServiceController.getAllEMIPaymentsByLoanApplicationId(loanApplicationID.value)}">
											<f:ajax execute="val" render=":installmentDetails"></f:ajax>
										</h:commandButton>
									</span>
								</h:form>
							</div>

							<div class="box-tools pull-right">
								<button type="button" class="btn btn-box-tool"
									data-widget="collapse" data-toggle="tooltip" title="Collapse">
									<i class="fa fa-minus"></i>
								</button>
								<button type="button" class="btn btn-box-tool"
									data-widget="remove" data-toggle="tooltip" title="Remove">
									<i class="fa fa-times"></i>
								</button>
							</div>
						</div>
						<!-- /.box-header -->
						<h:panelGroup id="installmentDetails" class="box-body">
							<h:dataTable class="table table-striped table-hover"
								value="#{paymentServiceController.emiPaymentsList}"
								var="emiDetails">
								<h:column>
									<f:facet name="header">
										<h:outputText value="Loan ID" />
									</f:facet>
									<h:outputText value="#{emiDetails.loanDetails.loanApplication.id}" />
								</h:column>
								<h:column>
									<f:facet name="header">
										<h:outputText value="Installment Number" />
									</f:facet>
									<h:outputText value="#{emiDetails.installmentNo}" />
								</h:column>
								<h:column>
									<f:facet name="header">
										<h:outputText value="EMI Amount" />
									</f:facet>
									<h:outputText
										value="#{emiDetails.emiAmount}" />
								</h:column>
								<h:column>
									<f:facet name="header">
										<h:outputText value="Late Payment Charge" />
									</f:facet>
									<h:outputText value="#{emiDetails.lateFineCharge}" />
								</h:column>
								<h:column>
									<f:facet name="header">
										<h:outputText value="Total Amount" />
									</f:facet>
									<h:outputText value="#{emiDetails.totalAmount}" />
								</h:column>
								<h:column>
									<f:facet name="header">
										<h:outputText value="Date Time" />
									</f:facet>
									<h:outputText value="#{emiDetails.emiDateTime}">
										<f:convertDateTime type="date" dateStyle="short"
												timeZone="#{appConfig.timeZone}" />
									</h:outputText>
								</h:column>
							</h:dataTable>
						</h:panelGroup>
						<!-- /.box-body -->
					</div>
					<!-- /.box -->
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row --> </section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<h:outputScript name="js/jquery.dataTables.min.js" target="body"></h:outputScript>
		<h:outputScript name="js/dataTables.bootstrap.min.js" target="body"></h:outputScript>

		<h:outputScript target="body">
		$(function () {
		    $("#example1").DataTable();
		    $('#example2').DataTable({
		      "paging": true,
		      "lengthChange": false,
		      "searching": false,
		      "ordering": true,
		      "info": true,
		      "autoWidth": false
			});
	  });
	</h:outputScript>
	</ui:define>

</ui:composition>